content/overview/installation/_index.en.md
Adds initial installation instructions.
=> Initial installation docs

i18n/en.yaml, i18n/fr.yaml, themes/godocs-1/exampleSite/i18n/en.yaml, themes/godocs-1/exampleSite/i18n/fr.yaml, themes/godocs-1/layouts/_default/contact.html
Clean up contact form, add Company for submission
=> Faq - clean up contact form

content/app-dev/create-actor/handlers.md, content/app-dev/create-actor/run.md, content/app-dev/create-actor/scaffold.md
When going through the wasmcloud actor tutorial, I noted that there were some discrepancies. I have updated the tutorial so that it is now straight-forward to follow it.
=> updated tutorial to new state of code

content/app-dev/create-actor/handlers.md, content/app-dev/create-provider/rust.md, content/app-dev/std-caps/_index.en.md
The crates have apparently been renamed.
=> Update actor example to use current crate names

content/releases/index.en.md
Draft PR for now as we haven't released this version yet (and not all of the PRs are merged)
=> 0.18.0 release docs

content/platform-builder/custom-host/fromspec.md
=> Adding documentation on requirements for building your own hosts

content/reference/host-runtime/healthchecks.md
Signed-off-by: Kevin Hoffman <autodidaddict@users.noreply.github.com>
=> Adding reference on health checks

content/overview/installation/_index.en.md, content/reference/host-runtime/safeshutdown.md
Signed-off-by: Kevin Hoffman <autodidaddict@users.noreply.github.com>
=> Adding safe shutdown section and link to it from installation section

themes/godocs-1/layouts/partials/head.html
Signed-off-by: Liam Randall <Liam.Randall@gmail.com>
=> adding hubspot tracking cookie

content/reference/lattice/provision.md
Signed-off-by: Kevin Hoffman <autodidaddict@users.noreply.github.com>
=> Closing #69. Adding doc page on provisioning a lattice

content/releases/index.en.md
=> Added release notes for 0.51.0

content/app-dev/create-provider/new-interface.md, content/app-dev/create-provider/rust.md
This pull requests fixes issue: https://github.com/wasmCloud/wasmcloud-dev-site/issues/87
It also adds some clarity to the tutorial about creating an interface and capability provider.
=> fixed inconsistencies

content/app-dev/create-provider/consuming.md, content/app-dev/create-provider/new-interface.md, content/app-dev/create-provider/rust.md
=> Corrected new interface/provider docs

content/app-dev/create-actor/update.md
=> Added note for hot reloading

content/app-dev/create-provider/new-interface.md, content/app-dev/create-provider/rust.md, content/faq/index.en.md
Signed-off-by: stevelr <steve@cosmonic.com>
=> fix broken links

content/reference/bindle/_index.en.md, content/reference/bindle/actor-bindles.md, content/reference/bindle/provider-bindles.md, content/reference/bindle/using-bindles.md
We shouldn't merge this until we cut 0.52, but this details the use of bindle fairly decently
=> docs(bindle): Adds new reference section for bindle

content/app-dev/debugging/_index.en.md, content/app-dev/debugging/actors.en.md, content/app-dev/debugging/common.en.md, content/app-dev/debugging/host.en.md, content/app-dev/debugging/providers.en.md
fixes #23 
Draft PR for now as this is unfinished, but committing the beginnings of our troubleshooting documentation
=> Troubleshooting guide

content/app-dev/create-actor/run.md, content/app-dev/create-actor/test.md, content/app-dev/create-actor/update.md
This will require an update to our `project-templates` repo, so keeping this as a draft until it's ready to merge.
Would still love feedback on wording and methodology.
edit: ready to merge once https://github.com/wasmCloud/project-templates/pull/34 is ready
=> Added section on unit testing actors

content/releases/index.en.md
=> added release notes for 0.53.0

README.md
=> added readme instructions for launch and files

content/overview/installation/_index.en.md
Signed-off-by: bwilloughby <bwilloughby@demark.com>
=> Fix link to Docker installation

content/overview/installation/_index.en.md
=> updated install version to 0.55.1

content/app-dev/create-provider/rust.md
Upgraded an old wasmbus dep in the create provider tutorial
=> Updated wasmbus to 0.10
